DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  content VARCHAR(255) NOT NULL,
  priority_id INTEGER REFERENCES priorities(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  checked BOOLEAN NOT NULL DEFAULT false,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);